# Nutika hoone inimeste liikumise analüüs (RFID-andmed)

Käesolev on 1-tunnine meeskonnaülesanne, mille eesmärk on analüüsida hoone ligipääsuandmeid `pandas` abil ning esitada peamised tulemused selgelt ja arusaadavalt.

## Andmestik
Andmestik sisaldab järgmisi veerge:
- `Timestamp` – sündmuse kuupäev ja kellaaeg
- `Employee_ID` – töötaja ID
- `Access_Point` – sündmuse tüüp (`Sisenemine`, `Väljumine`)
- `Department` – töötaja osakond

## Ülesanded
Lahenduses tuleb käsitleda järgmisi kohustuslikke osi:

1. Arvutage, kui palju inimesi viibib hoones igal tunnil.
2. Leidke töötajad, kes viibisid hoones kõige kauem, või töötajad, kelle viibimine ületas 10 tundi.
3. Tuvastage vähemalt üks ebaharilik juhtum, näiteks olukord, kus töötaja sisenes, kuid samal päeval väljumist ei registreeritud.

## Kohustuslik visualiseerimine
Koostage 2 kuni 3 graafikut, kasutades teeke `seaborn` ja `plotly`.

Nõuded:
- vähemalt 1 graafik teegiga `seaborn`
- vähemalt 1 interaktiivne graafik teegiga `plotly`

Sobivad näited:
- hoones viibivate inimeste arv ajas
- töötajate hoones viibimise kestuste võrdlus
- osakondade võrdlus kogutundide alusel

## Kohustuslik mini-veebirakendus
Koostage lihtne `Gradio` rakendus, kus kasutaja saab:
- laadida andmefaili
- näha vähemalt ühte tabelit ja graafikut

## Töökorraldus
Kuna tegemist on meeskonnaülesandega, on soovitatav jagada töö rollideks, näiteks:
- andmete puhastamine ja analüüs
- visualiseerimine `seaborn` ja `plotly` abil
- `Gradio` kasutajaliidese loomine

## Soovitused
- teisendage `Timestamp` kindlasti kuupäeva-kellaaja formaati
- sorteerige andmed ajaliselt
- selgitage töö lõpus lühidalt, millised tulemused saite

---

**Allpool olev notebook toetab käesoleva ülesande lahendamiseks vajalike `pandas`-oskuste omandamist ja rakendamist.**

## Soovituslik töökorraldus

Ülesande lahendamiseks on soovitatav järgida järgmisi samme:

1. Laadige CSV-fail `pandas` DataFrame'i.
2. Teisendage `Timestamp` kuupäeva-kellaaja formaati ja sorteerige andmed ajaliselt.
3. Arvutage tunnipõhine hoones viibivate inimeste arv.
4. Leidke pikema viibimisajaga töötajad või üle 10 tunni kestnud tööpäevad.
5. Tuvastage vähemalt üks ebaharilik juhtum.
6. Koostage 2 kuni 3 graafikut teekidega `seaborn` ja `plotly`.
7. Vormistage lihtne `Gradio` veebirakendus.

## Soovitatavad väljundid

- tabel analüüsi põhitulemustega
- 2 kuni 3 graafikut, millest vähemalt 1 on tehtud `seaborn` abil ja vähemalt 1 `plotly` abil
- töötav `Gradio` prototüüp
- lühike tekstiline kokkuvõte peamiste tähelepanekute kohta

## Milliseid graafikuid valida?

Allpool on lühike ülevaade sellest, milliseid graafikuid kasutatakse andmeanalüüsis kõige sagedamini, milleks need sobivad ja millal neid tasub koostada.

| Graafiku tüüp | Milleks kasutatakse? | Millal koostada? | Sobiv teek |
|---|---|---|---|
| Joongraafik (`line plot`) | Näitab muutust ajas | Kui soovite näidata, kuidas inimeste arv hoones muutub tundide või päevade lõikes | `seaborn`, `plotly` |
| Tulpdiagramm (`bar chart`) | Võrdleb erinevaid gruppe | Kui soovite võrrelda osakondi, töötajaid või eri kategooriaid | `seaborn`, `plotly` |
| Histogramm (`histogram`) | Näitab väärtuste jaotust | Kui soovite näha, kuidas jagunevad tööpäeva pikkused või hoones viibimise kestused | `seaborn`, `plotly` |
| Kastdiagramm (`boxplot`) | Toob esile mediaani, hajuvuse ja võimalikud erindid | Kui soovite võrrelda jaotusi osakondade vahel või leida ebatavaliselt pikki tööpäevi | `seaborn`, `plotly` |
| Soojuskaart (`heatmap`) | Näitab mustreid tabelkujuliste andmete sees värvide abil | Kui soovite näha, millistel päevadel ja kellaaegadel oli hoones kõige rohkem inimesi | `seaborn`, `plotly` |

## Kuidas valida sobiv graafik?

- Kui analüüsite muutust ajas, valige joongraafik.
- Kui võrdlete gruppe, valige tulpdiagramm.
- Kui uurite väärtuste jaotust, valige histogramm.
- Kui soovite leida erindeid või võrrelda hajuvust, valige kastdiagramm.
- Kui soovite näha mustreid kahe tunnuse lõikes, valige soojuskaart.

## Soovitus käesoleva ülesande jaoks

Selle ülesande puhul sobib hästi järgmine kombinatsioon:
- `seaborn` joongraafik hoones viibivate inimeste arvu muutumisest ajas
- `plotly` tulpdiagramm osakondade või töötajate võrdlemiseks
- soovi korral histogramm või kastdiagramm tööpäeva pikkuste analüüsimiseks

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from pathlib import Path

file_path = Path("access_log.csv")

df = pd.read_csv(file_path)
df["Timestamp"] = pd.to_datetime(df["Timestamp"])
df = df.sort_values(["Employee_ID", "Timestamp"]).reset_index(drop=True)

df.head()

## Töömall analüüsi alustamiseks

Allolev näide on mõeldud esialgse tööversiooni koostamise toetamiseks. Vajadusel kohandage veerunimesid, failinime ja analüüsi loogikat vastavalt oma andmestikule.

1-tunnise meeskonnatöö puhul on soovitatav lahendada ülesanne etapiviisiliselt:
- esmalt andmete puhastamine
- seejärel põhinäitajate arvutamine
- seejärel 2 kuni 3 graafiku koostamine teekidega `seaborn` ja `plotly`
- lõpuks `Gradio` prototüübi vormistamine

In [ ]:
events = df.copy()
events["event_delta"] = events["Access_Point"].map({"Sisenemine": 1, "Väljumine": -1})
events["date"] = events["Timestamp"].dt.date

entries = (
    events[events["Access_Point"] == "Sisenemine"]
    .copy()
    .rename(columns={"Timestamp": "entry_time"})
)
entries["visit_number"] = entries.groupby(["Employee_ID", "date"]).cumcount()

exits = (
    events[events["Access_Point"] == "Väljumine"]
    .copy()
    .rename(columns={"Timestamp": "exit_time"})
)
exits["visit_number"] = exits.groupby(["Employee_ID", "date"]).cumcount()

visits = entries.merge(
    exits[["Employee_ID", "date", "visit_number", "exit_time"]],
    on=["Employee_ID", "date", "visit_number"],
    how="left",
)

visits["hours_in_building"] = (
    visits["exit_time"] - visits["entry_time"]
).dt.total_seconds() / 3600

hourly_occupancy = (
    events.sort_values("Timestamp")
    .set_index("Timestamp")["event_delta"]
    .cumsum()
    .resample("1h")
    .max()
    .ffill()
    .fillna(0)
    .rename("people_in_building")
)

longest_stays = (
    visits.groupby("Employee_ID", as_index=False)["hours_in_building"]
    .sum()
    .sort_values("hours_in_building", ascending=False)
)

long_workdays = visits[visits["hours_in_building"] > 10].copy()
unusual_cases = visits[visits["exit_time"].isna()].copy()

department_summary = (
    visits.groupby("Department", as_index=False)["hours_in_building"]
    .sum()
    .sort_values("hours_in_building", ascending=False)
)

longest_stays.head()

In [ ]:
plt.figure(figsize=(12, 5))
sns.lineplot(x=hourly_occupancy.index, y=hourly_occupancy.values)
plt.title("People in the building by hour")
plt.xlabel("Time")
plt.ylabel("People count")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plotly_figure = px.bar(
    department_summary,
    x="Department",
    y="hours_in_building",
    title="Total hours in the building by department",
)
plotly_figure.show()

unusual_cases.head()

## Kohustuslik osa: lihtne `Gradio` prototüüp

Ülesande üheks kohustuslikuks osaks on väikese veebirakenduse koostamine. Eesmärk ei ole valmis toote loomine, vaid näidata, et andmeanalüüsi tulemusi on võimalik esitada ka kasutajaliidese kaudu.

Kui `gradio` ei ole paigaldatud, saab selle paigaldada näiteks käsuga `pip install gradio`.

In [ ]:
import gradio as gr


def summarize_access_file(uploaded_file):
    """Create a small access-log summary from an uploaded CSV file."""
    data = pd.read_csv(uploaded_file.name)
    data["Timestamp"] = pd.to_datetime(data["Timestamp"])
    data = data.sort_values("Timestamp").reset_index(drop=True)
    data["event_delta"] = data["Access_Point"].map({"Sisenemine": 1, "Väljumine": -1})

    hourly_summary = (
        data.set_index("Timestamp")["event_delta"]
        .cumsum()
        .resample("1h")
        .max()
        .ffill()
        .fillna(0)
        .rename("people_in_building")
        .reset_index()
    )

    return hourly_summary.head(24)


demo = gr.Interface(
    fn=summarize_access_file,
    inputs=gr.File(label="Upload CSV file"),
    outputs=gr.Dataframe(label="Hourly summary"),
    title="Building Access Analyzer",
    description="Upload an access log and preview hourly occupancy.",
)

# demo.launch()

# 🐼 Pandas ja DataFrame
### Abimaterjalid hoone ligipääsu analüüsi ülesande lahendamiseks

---

## Mis on pandas ja miks selline nimi?

**pandas** on Python teek andmetöötluseks. Nimi tuleb ingliskeelsest mõistest:

> **pan**el **da**ta → **pandas**

**Panel data** on majandusteaduse termin, mis tähendab andmeid, kus jälgitakse **samu objekte erinevatel ajahetkedel** — näiteks töötajate sisenemised hoonesse erinevatel kuupäevadel. Täpselt see, mida meie ülesandes analüüsime!

Teeki arendasid algselt **Wes McKinney** aastast 2008, alguses AQR Capital Managementi rahandusandmete analüüsimiseks.

---

### Pandas põhikontseptsioonid

| Objekt | Mis see on | Analoogia |
|--------|-----------|----------|
| `Series` | Ühedimensionaalne massiiv | Tabeli **üks veerg** |
| `DataFrame` | Kahemõõtmeline tabel | **Terve tabel** ridadega ja veergudega |

```
DataFrame
┌─────────────┬──────────┬────────────┬─────────────────────┐
│ töötaja_id  │   nimi   │  osakond   │     sisenemine      │
├─────────────┼──────────┼────────────┼─────────────────────┤
│    1234     │ Mart Tamm│     IT     │ 2024-01-15 07:25    │
│    5678     │ Kati Kask│     HR     │ 2024-01-15 10:50    │
└─────────────┴──────────┴────────────┴─────────────────────┘
       ↑            ↑                         ↑
   Series         Series                   Series
```

---
## 1. Teegi importimine ja CSV-faili laadimine

In [29]:
import pandas as pd

# Loe CSV-fail sisse
raw_df = pd.read_csv('data/access_log_1000.csv')

# Teisenda Timestamp datetime tüübiks
raw_df['Timestamp'] = pd.to_datetime(raw_df['Timestamp'])

# Pivot nii, et Sisenemine ja Väljumine muutuvad eraldi veergudeks
pivot_df = raw_df.pivot_table(
    index=['Employee_ID', 'Department'],
    columns='Access_Point',
    values='Timestamp',
    aggfunc='first'
).reset_index()

# Nimeta veerud ümber vastavalt oodatavale struktuurile
pivot_df.columns.name = None
df = pivot_df.rename(columns={
    'Employee_ID': 'töötaja_id',
    'Department': 'osakond',
    'Sisenemine': 'sisenemine',
    'Väljumine': 'väljumine'
})

# Lisa veerg "nimi"
df['nimi'] = 'Töötaja ' + df['töötaja_id'].astype(str)

# Arvuta tundide arv
df['tunde_hoones'] = (df['väljumine'] - df['sisenemine']).dt.total_seconds() / 3600

df

,töötaja_id,osakond,sisenemine,väljumine,nimi,tunde_hoones
0,1023,IT,2025-02-01 00:09:00,2025-02-01 14:02:00,Töötaja 1023,13.883333
1,1045,Logistika,2025-02-01 08:10:00,2025-02-01 15:54:00,Töötaja 1045,7.733333
2,1056,Logistika,2025-02-01 08:03:00,2025-02-01 15:28:00,Töötaja 1056,7.416667
3,1123,IT,2025-02-01 01:42:00,2025-02-01 12:49:00,Töötaja 1123,11.116667
4,1234,Logistika,2025-02-01 08:52:00,2025-02-02 15:42:00,Töötaja 1234,30.833333
5,2043,Müük,2025-02-01 08:01:00,2025-02-02 14:45:00,Töötaja 2043,30.733333
6,2045,IT,2025-02-01 01:13:00,2025-02-01 13:32:00,Töötaja 2045,12.316667
7,2100,IT,2025-02-01 08:31:00,2025-02-01 13:19:00,Töötaja 2100,4.800000
8,2101,IT,2025-02-01 08:37:00,2025-02-01 13:41:00,Töötaja 2101,5.066667
9,3456,Turvalisus,2025-02-01 08:54:00,2025-02-03 15:41:00,Töötaja 3456,54.783333
10,4567,Turvalisus,2025-02-01 08:25:00,2025-02-01 13:13:00,Töötaja 4567,4.800000
11,5002,Müük,2025-02-01 08:22:00,2025-02-01 15:27:00,Töötaja 5002,7.083333
12,5005,Müük,2025-02-01 08:35:00,2025-02-02 13:48:00,Töötaja 5005,29.216667
13,8342,IT,2025-02-01 08:42:00,2025-02-01 15:40:00,Töötaja 8342,6.966667

---
## 2. Andmete esmane uurimine

Enne analüüsi alustamist vaata alati, mis andmed sul on.

| Meetod / atribuut | Mida teeb |
|---|---|
| `df.shape` | Ridade ja veergude arv `(read, veerud)` |
| `df.dtypes` | Iga veeru andmetüüp |
| `df.info()` | Kokkuvõte: tüübid + mitte-null väärtused |
| `df.head(n)` | Esimesed n rida (vaikimisi 5) |
| `df.tail(n)` | Viimased n rida |
| `df.describe()` | Statistika: min, max, keskmine jne |

In [31]:
# Ridade ja veergude arv
print('Kuju (read, veerud):', df.shape)

# Veergude andmetüübid
print('\nAndmetüübid:')
print(df.dtypes)

Kuju (read, veerud): (14, 9)

Andmetüübid:
töötaja_id                  int64
osakond                    object
sisenemine         datetime64[ns]
väljumine          datetime64[ns]
nimi                       object
tunde_hoones              float64
sisenemine_tund             int32
väljumine_tund              int32
kuupäev                    object
dtype: object

In [32]:
# Täielik info — näitab ka mitte-null väärtuste arvu ja mälukasutust
# 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   töötaja_id       14 non-null     int64
 1   osakond          14 non-null     object
 2   sisenemine       14 non-null     datetime64[ns]
 3   väljumine        14 non-null     datetime64[ns]
 4   nimi             14 non-null     object
 5   tunde_hoones     14 non-null     float64
 6   sisenemine_tund  14 non-null     int32
 7   väljumine_tund   14 non-null     int32
 8   kuupäev          14 non-null     object
dtypes: datetime64[ns](2), float64(1), int32(2), int64(1), object(3)
memory usage: 1.0+ KB

In [33]:
# Statistika arvuliste veergude kohta
# mean, std, min, max, kvartilid jne
# mean = keskmine
# std = standardhälve (kui suur on andmete hajuvus keskmise ümber)
# min = minimaalne väärtus
# 25% = esimene kvartil (25% andmetest on sellest väärtusest väiksemad)
# 50% = mediaan (50% andmetest on sellest väärtusest väiksemad)
# 75% = kolmas kvartil (75% andmetest on sellest väärtusest väiksemad)
# max = maksimaalne väärtus 
df.describe()

,töötaja_id,sisenemine,väljumine,tunde_hoones,sisenemine_tund,väljumine_tund
count,14.000000,14,14,14.000000,14.000000,14.000000
mean,2867.285714,2025-02-01 06:52:34.285714688,2025-02-01 23:04:21.428571648,16.196429,6.428571,13.928571
min,1023.000000,2025-02-01 00:09:00,2025-02-01 12:49:00,4.800000,0.000000,12.000000
25%,1150.750000,2025-02-01 08:01:30,2025-02-01 13:34:15,6.995833,8.000000,13.000000
50%,2072.500000,2025-02-01 08:23:30,2025-02-01 15:27:30,9.425000,8.000000,14.000000
75%,4289.250000,2025-02-01 08:36:30,2025-02-02 08:19:30,25.383333,8.000000,15.000000
max,8342.000000,2025-02-01 08:54:00,2025-02-03 15:41:00,54.783333,8.000000,15.000000
std,2158.694136,NaN,NaN,14.756530,3.130846,1.071612

In [34]:
# Statistika mitte-arvuliste veergude kohta
# include='object' näitab ainult tekstiveergude statistikat
# Näiteks: unikaalsete väärtuste arv, kõige sagedasem väärtus (top) ja selle sagedus (freq)
df.describe(include='object')

       osakond          nimi     kuupäev
count       14            14          14
unique       4            14           1
top         IT  Töötaja 1023  2025-02-01
freq         6             1          14

---
## 3. Uute veergude lisamine (arvutused)

Meie ülesande jaoks on vaja arvutada, **mitu tundi töötaja hoones viibis**.

Kahe `datetime` väärtuse vahe annab `timedelta` objekti.
`.dt.total_seconds() / 3600` muudab selle tundideks.

In [30]:
# Lisa eraldi veerud kellaaegade jaoks — kasulik tunnianalüüsiks
df['sisenemine_tund'] = df['sisenemine'].dt.hour
df['väljumine_tund']  = df['väljumine'].dt.hour
df['kuupäev']         = df['sisenemine'].dt.date

df.head()

,töötaja_id,osakond,sisenemine,väljumine,nimi,tunde_hoones,sisenemine_tund,väljumine_tund,kuupäev
0,1023,IT,2025-02-01 00:09:00,2025-02-01 14:02:00,Töötaja 1023,13.883333,0,14,2025-02-01
1,1045,Logistika,2025-02-01 08:10:00,2025-02-01 15:54:00,Töötaja 1045,7.733333,8,15,2025-02-01
2,1056,Logistika,2025-02-01 08:03:00,2025-02-01 15:28:00,Töötaja 1056,7.416667,8,15,2025-02-01
3,1123,IT,2025-02-01 01:42:00,2025-02-01 12:49:00,Töötaja 1123,11.116667,1,12,2025-02-01
4,1234,Logistika,2025-02-01 08:52:00,2025-02-02 15:42:00,Töötaja 1234,30.833333,8,15,2025-02-01

---
## 4. Andmete filtreerimine

Filtreerimine töötab nii:
```python
df[df['veerg'] tingimus]
```
Tulemiks on uus DataFrame ainult sobivate ridadega.

In [35]:
# Töötajad, kes töötasid üle 10 tunni
yle_10h = df[df['tunde_hoones'] > 10]
print(f'Üle 10h töötanud kirjeid: {len(yle_10h)}')
yle_10h[['nimi', 'osakond', 'tunde_hoones', 'kuupäev']]

Üle 10h töötanud kirjeid: 7

            nimi     osakond  tunde_hoones     kuupäev
0   Töötaja 1023          IT     13.883333  2025-02-01
3   Töötaja 1123          IT     11.116667  2025-02-01
4   Töötaja 1234   Logistika     30.833333  2025-02-01
5   Töötaja 2043        Müük     30.733333  2025-02-01
6   Töötaja 2045          IT     12.316667  2025-02-01
9   Töötaja 3456  Turvalisus     54.783333  2025-02-01
12  Töötaja 5005        Müük     29.216667  2025-02-01

In [36]:
# Anomaaliad: töötaja sisenes, kuid ei väljunud (väljumine on tühi ehk NaN)
anomaaliad = df[df['väljumine'].isna()]
print(f'Anomaaliate arv: {len(anomaaliad)}')
anomaaliad[['töötaja_id', 'nimi', 'osakond', 'sisenemine']]

Anomaaliate arv: 0

Empty DataFrame
Columns: [töötaja_id, nimi, osakond, sisenemine]
Index: []

In [37]:
# Mitu veergu korraga + query meetod
# Töötajad IT osakonnast, kes veetsid üle 8 tunni
df.query('osakond == "IT" & tunde_hoones > 8')[['nimi', 'tunde_hoones']]

           nimi  tunde_hoones
0  Töötaja 1023     13.883333
3  Töötaja 1123     11.116667
6  Töötaja 2045     12.316667

---
## 5. Rühmitamine: groupby

`groupby` töötab kolme sammuna:

```
df.groupby('osakond')['tunde_hoones'].sum()
     ↑                    ↑             ↑
  rühmita              vali veerg    arvuta
```

| Funktsioon | Tähendus |
|---|---|
| `.sum()` | Summa |
| `.mean()` | Keskmine |
| `.count()` | Kirjete arv |
| `.max()` / `.min()` | Maksimaalne / minimaalne väärtus |
| `.agg([...])` | Mitu funktsiooni korraga |

In [38]:
# Kogutunnid osakondade kaupa — leiab kõige aktiivsema osakonna
osakond_tunnid = (
    df.dropna(subset=['tunde_hoones'])  # jäta välja anomaaliad
      .groupby('osakond')['tunde_hoones']
      .agg(['sum', 'mean', 'count'])
      .rename(columns={'sum': 'kokku_tundi', 'mean': 'keskmine', 'count': 'kirjeid'})
      .sort_values('kokku_tundi', ascending=False)
)
osakond_tunnid

            kokku_tundi   keskmine  kirjeid
osakond
Müük          67.033333  22.344444        3
Turvalisus    59.583333  29.791667        2
IT            54.150000   9.025000        6
Logistika     45.983333  15.327778        3

In [39]:
# Top 5 töötajat — kes viibis hoones kõige kauem kokku?
top_tootajad = (
    df.dropna(subset=['tunde_hoones'])
      .groupby(['töötaja_id', 'nimi', 'osakond'])['tunde_hoones']
      .sum()
      .reset_index()           # muuda grupeerimise tulemus tagasi DataFrame'iks
      .sort_values('tunde_hoones', ascending=False)
      .head(5)
)
top_tootajad

    töötaja_id          nimi     osakond  tunde_hoones
9         3456  Töötaja 3456  Turvalisus     54.783333
4         1234  Töötaja 1234   Logistika     30.833333
5         2043  Töötaja 2043        Müük     30.733333
12        5005  Töötaja 5005        Müük     29.216667
0         1023  Töötaja 1023          IT     13.883333

---
## 6. Inimeste arv hoones tunni kaupa

See on ülesande keerulisem osa. Peame iga tunni kohta (6–22) loendama,
mitu töötajat sel hetkel hoones viibis.

**Loogika:** töötaja on hoones tunnil `t`, kui:
```
sisenemine_tund <= t  JA  väljumine_tund >= t
```

In [40]:
tunnid = range(6, 23)  # 6:00 kuni 22:00
tulemused = {}

for tund in tunnid:
    mask = (
        (df['sisenemine_tund'] <= tund) &
        (df['väljumine_tund'].fillna(23) >= tund)  # NaN → 23 (eeldame, et on veel sees)
    )
    tulemused[tund] = mask.sum()

# Muuda sõnastik DataFrame'iks
tunnid_df = pd.DataFrame.from_dict(tulemused, orient='index', columns=['inimeste_arv'])
tunnid_df.index.name = 'tund'
tunnid_df = tunnid_df.reset_index()

# Leia tipptund ja tühjeim tund
tipptund  = tunnid_df.loc[tunnid_df['inimeste_arv'].idxmax(), 'tund']
tyhjim    = tunnid_df.loc[tunnid_df['inimeste_arv'].idxmin(), 'tund']

print(f'Tipptund:        {tipptund}:00 ({tunnid_df["inimeste_arv"].max()} inimest)')
print(f'Tühjeim kellaaeg: {tyhjim}:00 ({tunnid_df["inimeste_arv"].min()} inimest)')

tunnid_df

Tipptund:        8:00 (14 inimest)
Tühjeim kellaaeg: 16:00 (0 inimest)

    tund  inimeste_arv
0      6             3
1      7             3
2      8            14
3      9            14
4     10            14
5     11            14
6     12            14
7     13            13
8     14             8
9     15             6
10    16             0
11    17             0
12    18             0
13    19             0
14    20             0
15    21             0
16    22             0

---
## 7. Sorteerimine ja unikaalsed väärtused

Kiired abiülesanded.

In [41]:
# Sorteerimine — kahanev järjekord
df.dropna(subset=['tunde_hoones']).sort_values('tunde_hoones', ascending=False).head(5)

,töötaja_id,osakond,sisenemine,väljumine,nimi,tunde_hoones,sisenemine_tund,väljumine_tund,kuupäev
9,3456,Turvalisus,2025-02-01 08:54:00,2025-02-03 15:41:00,Töötaja 3456,54.783333,8,15,2025-02-01
4,1234,Logistika,2025-02-01 08:52:00,2025-02-02 15:42:00,Töötaja 1234,30.833333,8,15,2025-02-01
5,2043,Müük,2025-02-01 08:01:00,2025-02-02 14:45:00,Töötaja 2043,30.733333,8,14,2025-02-01
12,5005,Müük,2025-02-01 08:35:00,2025-02-02 13:48:00,Töötaja 5005,29.216667,8,13,2025-02-01
0,1023,IT,2025-02-01 00:09:00,2025-02-01 14:02:00,Töötaja 1023,13.883333,0,14,2025-02-01

In [42]:
# Unikaalsed osakonnad
print('Osakonnad:', df['osakond'].unique())

# Mitu kirjet osakonna kohta
print('\nKirjeid osakonna kohta:')
print(df['osakond'].value_counts())

Osakonnad: ['IT' 'Logistika' 'Müük' 'Turvalisus']

Kirjeid osakonna kohta:
osakond
IT            6
Logistika     3
Müük          3
Turvalisus    2
Name: count, dtype: int64


### Kasulikud lingid

#### Pandas
- [Pandas ametlik dokumentatsioon](https://pandas.pydata.org/docs/) - üldine juhend tabelandmete töötlemiseks.
- [read_csv parameetrid](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) - abiks CSV-faili laadimisel ja veergude seadistamisel.
- [groupby juhend](https://pandas.pydata.org/docs/user_guide/groupby.html) - vajalik rühmitamiseks ja kokkuvõtete arvutamiseks.
- [Datetime operatsioonid (.dt accessor)](https://pandas.pydata.org/docs/user_guide/timeseries.html) - kasulik kuupäeva ja kellaaja analüüsiks.
- [Pandas merge ja join](https://pandas.pydata.org/docs/user_guide/merging.html) - aitab ühendada erinevaid tabeleid või vahetulemusi.
- [Pandas reshaping ja pivot tabelid](https://pandas.pydata.org/docs/user_guide/reshaping.html) - sobib andmete ümberkujundamiseks ja risttabelite loomiseks.
- [Pandas missing values](https://pandas.pydata.org/docs/user_guide/missing_data.html) - vajalik puuduvate väärtuste leidmiseks ja käsitlemiseks.

#### Visualiseerimine
- [Seaborn ametlik dokumentatsioon](https://seaborn.pydata.org/) - üldine juhend kiirete statistiliste graafikute loomiseks.
- [Seaborn lineplot](https://seaborn.pydata.org/generated/seaborn.lineplot.html) - sobib muutuste näitamiseks ajas.
- [Seaborn barplot](https://seaborn.pydata.org/generated/seaborn.barplot.html) - sobib gruppide võrdlemiseks.
- [Seaborn histplot](https://seaborn.pydata.org/generated/seaborn.histplot.html) - aitab uurida väärtuste jaotust.
- [Seaborn boxplot](https://seaborn.pydata.org/generated/seaborn.boxplot.html) - aitab leida erindeid ja võrrelda hajuvust.
- [Plotly Python dokumentatsioon](https://plotly.com/python/) - üldine juhend interaktiivsete graafikute loomiseks.
- [Plotly Express sissejuhatus](https://plotly.com/python/plotly-express/) - lihtne viis alustada interaktiivsete graafikutega.
- [Plotly line chart](https://plotly.com/python/line-charts/) - sobib ajamuutuste interaktiivseks kuvamiseks.
- [Plotly bar chart](https://plotly.com/python/bar-charts/) - sobib kategooriate ja osakondade võrdlemiseks.
- [Plotly histogram](https://plotly.com/python/histograms/) - sobib kestuste ja väärtuste jaotuse näitamiseks.

#### Gradio
- [Gradio ametlik dokumentatsioon](https://www.gradio.app/docs) - üldine juhend veebiliidese loomiseks.
- [Gradio Quickstart](https://www.gradio.app/guides/quickstart) - kiire algus esimese rakenduse tegemiseks.
- [Gradio Interface](https://www.gradio.app/docs/gradio/interface) - peamine komponent lihtsa kasutajaliidese loomiseks.
- [Gradio Dataframe komponent](https://www.gradio.app/docs/gradio/dataframe) - võimaldab kuvada tulemusi tabelina.
- [Gradio File komponent](https://www.gradio.app/docs/gradio/file) - võimaldab kasutajal andmefaili üles laadida.

#### Lisamaterjalid
- [Python andmetüübid ja datetime moodul](https://docs.python.org/3/library/datetime.html) - abiks kuupäeva ja kellaaja töötlemisel Pythonis.
- [Matplotlib ametlik dokumentatsioon](https://matplotlib.org/stable/contents.html) - kasulik, kui soovite graafikute kujundust täpsemalt muuta.
- [Kaggle: Data Visualization](https://www.kaggle.com/learn/data-visualization) - lühike praktiline kursus visualiseerimise alustamiseks.
- [Kaggle: Pandas](https://www.kaggle.com/learn/pandas) - lühike praktiline kursus `pandas` põhioskuste kordamiseks.